apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/metallb
    repoURL: 'https://gitlab.com/kskewes/home-lab.git'
    targetRevision: HEAD
  project: home-lab
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
