---
remove_packages:
- zram-config

install_kernel:
- linux-image-4.4.167-1213-rockchip-ayufan-g34ae07687fce
- linux-firmware-image-4.4.167-1213-rockchip-ayufan-g34ae07687fce
- linux-headers-4.4.167-1213-rockchip-ayufan-g34ae07687fce
- board-package-rock64-0.8-152
- u-boot-rockchip-rock64-2017.09-rockchip-ayufan-1062-gbb4886a528
- linux-rock64-0.8
