---
# TODO(kskewes): Split into multiple files/roles

# Python 3 is probably already installed and we can specify 'ansible_python_interpreter: /usr/bin/python3' in inventory
# Uncomment below if using python 2 for some reason
# - name: Install Python if not already installed.
#   hosts: all
#   tags: python
#   gather_facts: false
#   tasks:
#   - name: Install Python 2.x
#     raw: test -e /usr/bin/python || (apt update && apt install -y python python-simplejson)
#     register: test
#     changed_when: test.stdout

- name: Base configuration of hosts
  hosts: all
  become: yes
  tasks:
  - name: Only run "update_cache=yes" if the last one '>3600' seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Update all packages to the latest version - aptitude safe-upgrade
    apt:
      upgrade: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Install standard tools
    apt:
      name: "{{ standard_tools }}"
      state: present
  - name: Install desired kernel
    apt:
      name: "{{ kernel_version }}"
      state: present
    register: new_kernel_installed
  - name: Reboot the server and wait for it to come back up.
    reboot:
      msg: Rebooting on new kernel
    when: new_kernel_installed is changed
  - name: Allow passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^%sudo ALL"
      line: "%sudo ALL=(ALL) NOPASSWD: ALL"
      validate: visudo -cf %s
  - name: "Set timezone to {{ timezone }}"
    timezone:
      name: "{{ timezone }}"

- name: Rock64 tasks
  hosts: rock64
  tags: rock64
  tasks:
  # When creating multiple host OS's from a single OS image, the machine-id will be identical.
  # This prevents Kubernetes, Weave CNI and other appplications from differentiating machines/nodes.
  - name: Verify if machine id has been rotated before
    stat:
      path: /etc/machine-id.rotated
    register: stat_result
  - name: Generate unique machine id
    become: yes
    shell: "cat /proc/sys/kernel/random/uuid > /etc/machine-id"
    when: stat_result.stat.exists == False
  - name: Generate rotated file
    become: yes
    file:
      path: /etc/machine-id.rotated
      state: touch
    when: stat_result.stat.exists == False
  - name: Set hostname
    become: yes
    hostname: name={{ inventory_hostname }}
    when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  - name: Ensure hostname in /etc/hosts
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: '^(127.0.1.1)\s*(rock64)$'
      line: "127.0.1.1 {{ inventory_hostname }}"
      backrefs: yes
      owner: root
      group: root
      mode: 0644
