---
# TODO(kskewes): Split into multiple files/roles

- name: Base configuration of hosts
  hosts: all:!edgeos
  become: yes
  pre_tasks:
  - name: Install python for Ansible
    become: yes
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
    changed_when: False
  tasks:
  - name: Setup users
    user:
      name: karl
      comment: Karl
      groups:
      - sudo
      # - docker  ## Only possible once installed (kubespray does)
      append: yes
      shell: /bin/bash
      state: present
  - name: Add authorized keys
    authorized_key:
      user: karl
      key: "{{ lookup('file', '/home/karl/.ssh/id_rsa.pub') }}"
      state: present
  - name: Only run "update_cache=yes" if the last one '>3600' seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
      autoremove: yes
      autoclean: yes
  - name: Install packages
    apt:
      name: "{{ install_packages }}"
      state: present
  - name: Remove packages
    apt:
      name: "{{ remove_packages }}"
      state: absent
  - name: Allow passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^%sudo ALL"
      line: "%sudo ALL=(ALL) NOPASSWD: ALL"
      validate: visudo -cf %s
  - name: "Set timezone to {{ timezone }}"
    timezone:
      name: "{{ timezone }}"
  - name: Set hostname
    hostname: name={{ inventory_hostname }}
    when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  - name: Ensure kernel modules load on boot
    copy:
      dest: /etc/modules-load.d/ipip.conf
      content: |
        ipip
    notify: reboot_required
  handlers:
  - name: Reboot the server and wait for it to come back up.
    become: yes
    reboot:
      msg: Rebooting on change in kernel/zram/module change
    listen: reboot_required

- name: Rook Ceph tasks
  hosts: kube-storage
  become: yes
  tags: rook-ceph
  tasks:
  - name: Load kernel modules  # Rook Ceph
    modprobe:
      name: "{{ item }}"
      state: present
    with_items: "{{ kernel_modules }}"
  - name: Add kernel modules to autoload file
    lineinfile:
      create: yes
      dest: "/etc/modules-load.d/rook-ceph.conf"
      line: "{{ item }}"
      state: present
      owner: root
      group: root
      mode: 0644
    with_items: "{{ kernel_modules }}"

- name: Rock64 tasks
  hosts: rock64
  become: yes
  tags: rock64
  tasks:
  - name: Disable Armbian zram-config service
    service:
      name: armbian-zram-config
      enabled: no
      state: stopped
    notify: reboot_required
  # When creating multiple host OS's from a single OS image, the machine-id will be identical.
  # This prevents Kubernetes, Weave CNI and other appplications from differentiating machines/nodes.
  - name: Verify if machine id has been rotated before
    stat:
      path: /etc/machine-id.rotated
    register: stat_result
  - name: Generate unique machine id
    shell: "cat /proc/sys/kernel/random/uuid > /etc/machine-id"
    when: stat_result.stat.exists == False
  - name: Generate rotated file
    file:
      path: /etc/machine-id.rotated
      state: touch
    when: stat_result.stat.exists == False
  - name: Ensure hostname in /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^(127.0.1.1)\s*(rock64)$'
      line: "127.0.1.1 {{ inventory_hostname }}"
      backrefs: yes
      owner: root
      group: root
      mode: 0644
  - name: Load bluetooth module on startup
    copy:
      content: "btusb"
      dest: /etc/modules-load.d/btusb
  - name: Load bluetooth module
    modprobe:
      name: btusb
      state: present
  - name: Install bluetooth packages
    apt:
      name: ["bluetooth", "bluez"]
      state: present
  - name: Start bluetooth service
    service:
      name: bluetooth
      enabled: yes
      masked: no
      state: restarted
  handlers:
  - name: Reboot the server and wait for it to come back up.
    become: yes
    reboot:
      msg: Rebooting on change in kernel/zram/module change
    listen: reboot_required
